version: "3.7"

# docker-compose -f ./docker-compose.yml up -d
# java --enable-preview -jar demo.jar

services:
  postgres:
    image: docker.io/library/postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring
    ports:
      - "5432:5432"